### ISSUE TITLE
edit  Product

### ISSUE THREAD

**Issue by zanjs** [lavender/lavender#21]
FatalErrorException in EditProduct.php line 8:
Class 'App\Handlers\Forms\Backend\EditEntity' not found

**Comment by SharkIng** [comment]
From a search, the EditEntity and handle_entity function are not exist, i think its because this framework still under development. developer did not add that into file yet.

**Comment by SharkIng** [comment]
#19 its same issue here.

**Comment by snipertomcat** [comment]
I fixed this issue and submitted a pull request for it. You can find it [here](https://github.com/lavender/lavender/pull/37)

**Comment by zanjs** [comment]
@SharkIng @snipertomcat  Thinks!
