### ISSUE TITLE
 ErrorException in Encrypter.php line 303: Function mcrypt_get_iv_size() is deprecated

### ISSUE THREAD

**Issue by Rolanddoda** [lavender/lavender#36]
Hello i am getting this error 
![image](https://cloud.githubusercontent.com/assets/18482346/24712241/9eb392d2-1a22-11e7-8b8c-eed912bed96e.png)

**Comment by gera-mtz** [comment]
Is because an php version. If you use the 7.0 or 7.1 version, change to 5.6. I do work
