### ISSUE TITLE
Getting an error 

### ISSUE THREAD

**Issue by Rexweb** [lavender/lavender#5]
I have configured the app and when I am trying to run it then getting the following error:

Call to undefined function workflow() 

Can you please let me know whats wrong with it and if I am missing anything.

Your urgent help would be really appreciated!

Thanks

**Comment by nuzcom** [comment]
1. Symfony\Component\Debug\Exception\FatalErrorException
…\vendor\ryaan-anthony\lavender-contact-form\src\config\layout.php18 

This is the path where that function has been called.

May be this can help to understand the issue.

Thanks!

**Comment by ryaan-anthony** [comment]
yep I'm aware. the project is in active development, we aren't ready to provide alpha builds just yet. maybe in a few weeks!

thank you for your interest, I'll close this issue once the build is ready!

**Comment by ryaan-anthony** [comment]
we have tagged builds now that will maintained in their last know stable state. closing this issue, and thanks for your feedback!
