### ISSUE TITLE
SQL Error: Field 'description' doesn't have a default value - when running lavender:install

### ISSUE THREAD

**Issue by schystz** [lavender/lavender#6]
php artisan lavender:install
Created Migration: 2015_01_25_100104_install_lavender_1422180064
Migration table created successfully.
Migrated: 2015_01_25_100104_install_lavender_1422180064
Would you like to create a new store? [yes|no] yes
Would you like to create a new theme? [yes|no] yes
Enter a code: (Default = default)
Enter a name: (Default = Default Theme)
Would you like to create a new category? [yes|no] yes
Enter a name: (Default = Default Category)
SQLSTATE[HY000]: General error: 1364 Field 'description' doesn't have a default value (SQL: insert into `catalog_category` (`url`, `name`, `updated_at`, `created_at`) values (catalog/category/54c4beedd19ae, Default Category, 2015-01-25 10:01:17, 2015-01-25 10:01:17))#0 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ca...', Array, Object(Closure))
#1 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ca...', Array, Object(Closure))
#2 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ca...', Array)
#3 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ca...', Array)
#4 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1896): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Lavender\Entity\Database\QueryBuilder), 'insert into `ca...', Array, 'id')
#5 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/lavender/framework/src/Entity/Database/QueryBuilder.php(63): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 [internal function]: Lavender\Entity\Database\QueryBuilder->insertGetId(Array, 'id')
#7 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(935): call_user_func_array(Array, Array)
#8 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1579): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#9 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1579): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#10 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1549): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1455): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /Users/schystz/Developer/php/laravel/lavendersample.com/src/Catalog/Commands/CreateCategory.php(64): Illuminate\Database\Eloquent\Model->save()
#13 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): Lavender\Catalog\Commands\CreateCategory->fire()
#14 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(128): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /Users/schystz/Developer/php/laravel/lavendersample.com/src/Catalog/CatalogServiceProvider.php(69): Illuminate\Console\Command->call('lavender:catego...', Array)
#18 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/lavender/framework/src/Core/Commands/InstallLavender.php(37): Lavender\Catalog\CatalogServiceProvider->Lavender\Catalog\{closure}(Object(Lavender\Core\Commands\InstallLavender))
#19 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): Lavender\Core\Commands\InstallLavender->fire()
#20 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Lavender\Core\Commands\InstallLavender), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /Users/schystz/Developer/php/laravel/lavendersample.com/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /Users/schystz/Developer/php/laravel/lavendersample.com/artisan(59): Symfony\Component\Console\Application->run()
#26 {main}schystz:lavendersample.com

**Comment by ryaan-anthony** [comment]
i have tagged the latest stable build which resolves this issue, thanks for your feedback!

**Comment by schystz** [comment]
Cool thanks!

**Comment by schystz** [comment]
Hi Ryaan, how do I use the latest lavender build? I tried to setup a new project by following the instructions on README but I'm still getting the same error.

**Comment by ryaan-anthony** [comment]
Interesting, what version of mysql? 

I made a fix that would allow longtext fields to be nullable which should resolve this particular issue.

**Comment by schystz** [comment]
Server version: 5.6.21 MySQL Community Server (GPL)
Unchecking NOT NULL on catalog_category.description is a temporary fix for me.

**Comment by ryaan-anthony** [comment]
ah, i was still on 5.5 thanks for the feedback!
