### ISSUE TITLE
Is Admin Username Necessary?

### ISSUE THREAD

**Issue by MattDunbar** [lavender/lavender#8]
Is there any reason to have a username vs using email for everything for admins? I can't imagine a situation where an admin wouldn't want another to know their email (which is the only justification I see for usernames).

If having a display name is essential I'd suggest going with real identities for an admin where accountability is essential (first name / last name / maybe company).

https://github.com/lavender/lavender/blob/master/app/Admin/config/entity.php#L14-L19

**Comment by ryaan-anthony** [comment]
sounds good to me, usernames were used (mostly) to test the flexibility of the auth module, it works but you've got a good point so i'll just ditch admin usernames in my next round of commits

**Comment by ryaan-anthony** [comment]
build passed with l5 refactor sans admin username
